email_analysis_task:
  description: >
    Analyse le contenu textuel suivant pour identifier s’il contient des signes de fraude, d’hameçonnage (phishing) ou de tentative d’arnaque.
    Tu dois uniquement te baser sur le texte (pas sur les liens ni les pièces jointes).
    Voici le mail à analyser : {mail}
  expected_output: >
    Un rapport clair indiquant :
    - Si le message semble suspect ou non
    - Les signaux ou expressions qui paraissent inhabituels ou inquiétants
    - Une évaluation globale du risque (faible, modéré, élevé)
    - Des recommandations éventuelles (ignorer, répondre, signaler, etc.)
  agent: email_content_analyst


reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
